services:
  web:
    image: websec-scanner:latest   # usa a imagem com a tag que vocÃª criou
    build: .
    container_name: enhanced-web-scanner
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./reports:/app/reports
      - ./scanner_db.sqlite:/app/scanner_db.sqlite
    restart: unless-stopped
